### ISSUE TITLE
how to show properties in tabular form when clicking on node and relations

### ISSUE THREAD

**Issue by veerareddyakkili** [Nhogs/popoto-examples#13]
When i click on node or relation it has to show the properties in Tabular form.

**Comment by Popotojs** [comment]
The click events are already used to manipulate the graph, (see the list of [basic actions here](https://github.com/Nhogs/popoto/wiki/Basic-action) for details) but you can customize the text displayed on nodes with [```getTextValue```](https://github.com/Nhogs/popoto/wiki/Node-configuration#get-text-value) and display for example the full list of properties.
