### ISSUE TITLE
Node ID is being displayed and not label name

### ISSUE THREAD

**Issue by veerareddyakkili** [Nhogs/popoto-examples#14]
when using popotojs.zip, it is showing node label names on the node but when using css-customization example it is showing node id's with the same data. what is the diff between both the examples.

**Comment by Popotojs** [comment]
You can customize what you want to display on a node using either an attribute value with ```displayAttribute``` config, see detail on [documentation here](https://github.com/Nhogs/popoto/wiki/Node-configuration#display-attribute)
or by using the ```getTextValue``` config which lets you generate the exact text you want from node properties see [details here](https://github.com/Nhogs/popoto/wiki/Node-configuration#get-text-value)
